### ISSUE TITLE
[virtualization][kubernetes_administration] TKGS how to SSH into nodes

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/rootpages#439]
https://docs.vmware.com/en/VMware-vSphere/7.0/vmware-vsphere-with-tanzu/GUID-37DC1DF2-119B-4E9E-8CA6-C194F39DDEDA.html

Here is an example script automating that access: https://github.com/josemzr/vsphere-k8s-scripts/blob/master/tkg-add-ca.sh

**Comment by ekultails** [comment]
This first requires a jump box created with the same Frontend network.

https://docs.vmware.com/en/VMware-vSphere/7.0/vmware-vsphere-with-tanzu/GUID-6DE3E58B-6AE3-4ABD-ABCC-2221B4230908.html

Alternatively, add a VNIC to the Frontend network on a VM.

https://kb.vmware.com/s/article/2147155

Either way, the VM has to be in the same cluster to be attached to the vDS (virtual distributed switch).

**Comment by ekultails** [comment]
Alternatively, if possible, create a Pod running Photon OS on the cluster and install+run SSH. Then access the Pod via SSH.

https://docs.vmware.com/en/VMware-vSphere/7.0/vmware-vsphere-with-tanzu/GUID-587E2181-199A-422A-ABBC-0A9456A70074.html

**Comment by ekultails** [comment]
Each TanzuKubernetesCluster will have virtual machines created in vSphere that have the network CIDR of `10.244.0.<UNKNOWN>/28`. To find the exact CIDR, log into the NSX-T Manager and go to Networking > Segements.

**Comment by ekultails** [comment]
Update on what happens with more than 14 nodes:

I tried deploying a TanzuKubernetesCluster with 18 nodes with the size/capacity of best-effort-xsmall. The Supervisor cluster crashed. I'm unsure if this is because my lab environment is small or because of a size limitations. What I do know is that it still created a /28 network for the VMs and that. Also, all of my VMs were created but only the first control plane node started.

According to the documentation, the recommended maximum is 3 control plane nodes and 150 worker nodes.

https://docs.vmware.com/en/VMware-vSphere/7.0/vmware-vsphere-with-tanzu/GUID-4E68C7F2-C948-489A-A909-C7A1F3DC545F.html#:~:text=A%20cluster%20with%20zero%20worker,a%20reasonable%20limit%20is%20150.
